### ISSUE TITLE
Planned adapters

### ISSUE THREAD

**Issue by Nyholm** [php-cache/adapter-bundle#6]
These are the adapters that we should support. 

* [x] Apc https://github.com/php-cache/apc-adapter
* [x] Apcu https://github.com/php-cache/apcu-adapter
* [x] Array https://github.com/php-cache/array-adapter
* [x] Chain https://github.com/php-cache/chain-adapter
* [ ] Couchbase ?
* [x] Doctrine Cache
* [ ] File
* [x] Filesystem (flysystem) https://github.com/php-cache/filesystem-adapter
* [x] Memcache https://github.com/php-cache/memcache-adapter
* [x] Memcached https://github.com/php-cache/memcached-adapter
* [ ] Mongodb https://github.com/php-cache/mongodb-adapter
* [ ] PHPFile ?
* [x] Predis https://github.com/php-cache/predis-adapter
* [x] Redis https://github.com/php-cache/redis-adapter
* [ ] Riak ? 
* [ ] SQLite
* [x] Void https://github.com/php-cache/void-adapter
* [ ] WinCache ?
* [ ] Xcache ? 
* [ ] ZendData

**Comment by Nyholm** [comment]
Im starting with void adapter now

**Comment by Nyholm** [comment]
Im starting with the array adapter

**Comment by Nyholm** [comment]
Im starting with apc

**Comment by Nyholm** [comment]
Im starting with apcu

**Comment by Nyholm** [comment]
Starting with the filesystem adapter

**Comment by Nyholm** [comment]
Im starting with mongo

**Comment by Nyholm** [comment]
Staring with PHPredis

**Comment by Nyholm** [comment]
Starting with the Chain

**Comment by cakper** [comment]
Well done mate :) congrats
